name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            target: x86_64-apple-darwin
            arch: intel
          - platform: macos-latest
            target: aarch64-apple-darwin
            arch: arm64
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Get version
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          echo "VERSION=$((Get-Content package.json | ConvertFrom-Json).version)" >> $env:GITHUB_ENV

      - name: Get version
        if: matrix.platform == 'macos-latest'
        shell: bash
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: 剪贴板历史记录 v${{ env.VERSION }}
          draft: true
          prerelease: false

      - name: Install WiX
        if: matrix.platform == 'windows-latest'
        run: |
          nuget install WiX -Version 3.11.2

      - name: Build the app
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: '剪贴板历史记录 v${{ env.VERSION }}'
          releaseBody: |
            剪贴板历史记录工具新版本发布！

            ### 下载
            - Windows 用户：选择 .exe 文件
            - macOS Intel 用户：选择带 intel 的文件
            - macOS Apple Silicon 用户：选择带 arm64 的文件
          releaseDraft: true
          prerelease: false
          args: --target ${{ matrix.target }}

      - name: List Build Output (Debug)
        if: matrix.platform == 'windows-latest'
        run: |
          ls src-tauri/target/release/bundle/nsis/
        shell: bash

      - name: Upload Release Assets (Windows)
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/nsis/剪贴板历史记录_${{ env.VERSION }}_x64-setup.exe
          asset_name: 剪贴板历史记录_${{ env.VERSION }}_x64-setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Upload Release Assets (macOS DMG)
        if: contains(matrix.platform, 'macos')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/dmg/剪贴板历史记录_${{ env.VERSION }}_${{ matrix.arch }}.dmg
          asset_name: clipboard_history_${{ env.VERSION }}_${{ matrix.arch }}.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload Release Assets (macOS APP)
        if: contains(matrix.platform, 'macos')
        run: |
          cd src-tauri/target/release/bundle/macos
          tar -czf clipboard_history_${{ env.VERSION }}_${{ matrix.arch }}.app.tar.gz 剪贴板历史记录.app

      - name: Upload macOS APP Archive
        if: contains(matrix.platform, 'macos')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src-tauri/target/release/bundle/macos/clipboard_history_${{ env.VERSION }}_${{ matrix.arch }}.app.tar.gz
          asset_name: clipboard_history_${{ env.VERSION }}_${{ matrix.arch }}.app.tar.gz
          asset_content_type: application/gzip
